### ISSUE TITLE
I need a FAQ :-)

### ISSUE THREAD

**Issue by gitgetgot** [da2x/fluxfonts#12]
Hi,
I like the idea (and thank you for developing such a useful tool), but can not imagine how it works.

Would you please explain:

-Where do I find a MacOSX installer?

-How does it run on windows? As a service, or just a simple.exe which the user must start everytime by hand? (Same for MacOSX)

-Has it an autoupdate? Or does the user needs to check manually?

-Will it delete existing fonts?

-Will the created fonts bedazzle Winword/Pages or any other program, which uses fonts? (i.e. will Photoshop rescan the Fonts folder on every start and re-index the new fonts, which will probably take a wile)

-How much CPU will it cost? And when?

-Do I need a doctor's degree for this? WTF is a makefile...? ;-D

**Comment by da2x** [comment]
> -Where do I find a MacOSX installer?

There isn’t one. I won’t pay Apple for the privilege of a binary deliverable. You’ll need to compile it from sources. See bottom.

> -How does it run on windows? As a service, or just a simple.exe which the user must start everytime by hand? (Same for MacOSX)

It runs as a scheduled task on Windows and as a launched service daemon on macOS.

> -Has it an autoupdate? Or does the user needs to check manually?

No. There have been virtually no need to ship updates. The program is very simple. An auto-update mechanism would require way more code and upkeep than the program itself.

> -Will it delete existing fonts?

It will install and remove a set of randomly generated fonts. You may see some strange font names in programs that list installed fonts. 

> -Will the created fonts bedazzle Winword/Pages or any other program, which uses fonts? (i.e. will Photoshop rescan the Fonts folder on every start and re-index the new fonts, which will probably take a wile)

Kind of but not really. Only the fonts that have changed since the last time you ran the program will need to be rescanned. The fonts don’t contain font glyphs so programs don’t spend any time caching their glyph renderings.

> -How much CPU will it cost? And when?

It runs every 2–40 minutes. It’s CPU usage is low that it shouldn’t even register in Activity Monitor: Energy after a month’s runtime.

> -Do I need a doctor's degree for this? WTF is a makefile...? ;-D

A Makefile is file containing compilation instruction. It instructs the `make` command line program how to to build the program and supporting files from source code.

Instructions to build your first program from source code:

0. Install Xcode from the App Store. Run it once and accept installing the additional tools (it will prompt you on first run).
1. Download it and unzip https://github.com/da2x/fluxfonts/archive/v2.0.zip
2. Open the Terminal program (in /Applications/Utilities/Terminal.app)
3. Type `cd ` (cd plus space), and drag and drop the downloaded folder to the Terminal window. Press Enter. (This **c**hanges the working **d**irectory to the one containing the code.)
4. Type `make` and press Enter. (This compiles/“makes” the program.)
5. If there are no errors, type `sudo make install install-launchd` and press Enter. (su-do, switch-user do, “change to the admin user and do the make command”)
6. Enter you password and press Enter.

You’ve built and installed your first program from code! It’s also installed and should be running. Type `ps aux | grep fluxfont` to see that the program is running. launchd will restart it after reboot.

**Comment by gitgetgot** [comment]
Wow! Thats a FAQ a lot programs are missing!
Thank you very much.
Now, everything is crystal-clear.

I fully agree to your statements and be happy that you give others a chance to help themselfes :-)


As for the Install/making:
I get this error, at step 4.
```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fluxfontd] Error 1
```
So I'm out here.

Good luck to all who give it another try!

Cheers & Thank you!
